language: cpp
compiler:
    - gcc

notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
            - upi.bhalla@gmail.com

        on_success: change
        on_failure: always

before_install:
    - sudo apt-get update -qq
    - sudo ./.travis_prepare_linux.sh

script: 
    - ./.travis_build.sh
