dist: trusty
sudo: required
language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

#matrix:
#    allow_failures:
#        - clang

before_script:
    - sudo apt-get install -qq libxml2-dev libbz2-dev
    - sudo apt-get install -qq libhdf5-serial-dev libgsl0-dev
    - sudo apt-get install -qq make cmake
    - sudo apt-get install -qq python-numpy python-matplotlib python-networkx
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libgsl0-dev libqt4-dev python-sip python-qt4
    - sudo apt-get install -qq python-qt4-dev
    - sudo apt-get install -qq python-pip
    - sudo apt-get install -qq libgraphviz-dev
    - sudo apt-get install -qq python-numpy python-matplotlib

install:
    - echo "nothing to do here"

script:
    - ## CMAKE based flow
    - mkdir -p _GSL_BUILD && cd _GSL_BUILD && cmake -DMOOSE_VERSION=3.2 \
        -DPYTHON_EXECUTABLE=/usr/bin/python ..
    - make -j4 && ctest --output-on-failure
