language: python
python:
    - '2.7'
notifications:
    - dilawar.s.rajput@gmail.com
    - bhalla@ncbs.res.in
    - goel.aviral@gmail.com

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libopenscenegraph-dev
    - sudo apt-get install -y libqt4-dev
    - sudo apt-get install -y libqt4-opengl-dev
    - sudo apt-get install -y python-qt4-gl
    - sudo apt-get install -y python-qt4-dev
    - sudo apt-get install -y python-sip-dev
script: 
    - mkdir -p _build
    - cd _build
    - cmake ..
    - make -j`nproc`

cache:
    - apt
