sudo: required
language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com
        on_success: change
        on_failure: always

env:
    - CTEST_MODEL=Nightly
cache: apt

#matrix:
#    allow_failures:
#        - clang

before_script:
    - sudo apt-get install -qq libxml2-dev libbz2-dev
    - sudo apt-get install -qq libhdf5-serial-dev
    - sudo apt-get install -qq make cmake
    - sudo apt-get install -qq python-numpy python-matplotlib python-networkx
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libgsl0-dev
    - sudo apt-get install -qq python-pip
    - sudo apt-get install -qq libgraphviz-dev
    - sudo apt-get install -qq python-numpy

install:
    - echo "nothing to do here"

script:
    - ## CMAKE based flow
    - mkdir -p _GSL_BUILD && cd _GSL_BUILD && cmake -DMOOSE_VERSION=3.1.1 -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python ..
    - make && ctest --output-on-failure
    - cd .. # Now with boost.
    - mkdir -p _BOOST_BUILD && cd _BOOST_BUILD && cmake -DMOOSE_VERSION=3.1.1 -DWITH_BOOST=ON -DDEBUG=ON -DPYTHON_EXECUTABLE=/usr/bin/python ..
    - make && ctest --output-on-failure
    - cd .. 
    - echo "All done. Phew"
